server:
  port: 5000

app:
  telegram-bot:
    name:
    token:
    webhook-path:

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  datasource:
    url:
    username: test
    password: test
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yml
  servlet:
    multipart:
      max-file-size: 10485760
      max-request-size: 20971520
      file-size-threshold: 0
      location: /tmp


